### PR TITLE
Fixes for macOS CoreMIDI

### PR DESCRIPTION
**Pull request by mmontag**
This addresses two big problems on macOS: 
- MIDI devices show up as empty string
- Stuck notes

### CODE REVIEW

**Comment by mmontag** [comment]
@skjelten have a chance to look at this one?

**Comment by skjelten** [comment]
I am on a vacation trip at the moment, but will have a look at it next week when I am back home.

Hopefully we can also make the next release soon, I just feel that current git master might need some improvements before being ready for a release.

**Comment by skjelten** [comment]
Finally home and back in front of the PC again. I have some vague memories of ignoring this issue when I wrote the mac MIDI code the first time (I am not much of a mac user), so it is very nice to see it being fixed. The code you write looks as usual very good, but I do have two comments:
* Is there any particular reason for you to use `printf` instead of `cout`? If you really want to use `printf` I think you need to include `cstdio.h` (see line 61 midi_input_code.cc). I guess you might want to remove this line anyways, or put it behind a if(0)?
* A relatively large part of the total diff, in number of code lines, is just moving parenthesis and changing from multiple spaces to 1 tabulator for indentation. I guess a lot could be said about the GNU coding guidelines (and my sloppy adherence), but until we agree on something else I prefer that we just keep the style as is. Much appreciated if you slim down the diff to only include lines that has actual code change.

As a final note I have to say that I really dislike it when people nit pick about tiny details and stifle innovation just to get the number of spaces right, so I promise I will not complain about coding style (ref my last point) in future PRs as long as it is mostly in line with current style :slightly_smiling_face:

**Comment by mmontag** [comment]
Oops, I didn't mean to leave the `printf` statement.  I prefer `printf` because it's easier to read and easier to format rather than by concatenation. (Look forward to using `std::print` in C++23.)
Also, I was thinking we could add some defines like `EMUSC_DEBUG` to replace the `if(0)`.

I'll remove the whitespace change, but my edit changed tabs to spaces. The indentation looked messed up in my editor due to tab width.  

 Maybe we can pick a clang-format style that IDEs can pick up on - https://zed0.co.uk/clang-format-configurator.  Personally, I like the Google style with a slightly increased ColumnLimit.

**Comment by skjelten** [comment]
> Oops, I didn't mean to leave the `printf` statement. I prefer `printf` because it's easier to read and easier to format rather than by concatenation. (Look forward to using `std::print` in C++23.) Also, I was thinking we could add some defines like `EMUSC_DEBUG` to replace the `if(0)`.

I agree that the printf statement at times is much nicer, especially when printing values with fixed number of digits and in different number formats. I was not aware of the `std::print` , but seems like a good alternative to `std::cout` in the future.

A `EMUSC_DEBUG` variable is a good idea and I am pretty sure I used that variable about a year ago, but for some reason it never ended up in git. Feel free to use it if you like. We could perhaps use a number from 0-9 indicating how much output we want, similarly to how e.g. gstreamer does it with [GST_DEBUG](https://gstreamer.freedesktop.org/documentation/tutorials/basic/debugging-tools.html?gi-language=c).

> 
> I'll remove the whitespace change, but my edit changed tabs to spaces. The indentation looked messed up in my editor due to tab width.

Ahh, that is right. Emacs has a really strange default policy on use of spaces and tabulation. I tend to forget this because emacs hides this oddity for me as long as I stay in emacs. It absolutely makes more sense to only use spaces.

> Maybe we can pick a clang-format style that IDEs can pick up on - https://zed0.co.uk/clang-format-configurator. Personally, I like the Google style with a slightly increased ColumnLimit.

I learned to code C when Kernighan & Ritchies "C Programming Language" was the bible of coding. Then I adopted some kind of random GNU inspired C++ variation of that. I am more than happy to change this to something more "standardized". The Google style is fine for me, but with two comments:
* I prefer the start bracket "{" for method / function definitions (e.g. main()) to be on a new line, and not on the same line as the definition
* I prefer that lines are < 80 characters when practically possible. It is perfectly OK with exceptions to this rule when it makes no sense to split the line

**Comment by skjelten** [comment]
I guess we should just push for a new release. Do you want to update this patch first? Moving to something like google style I suggest we do in one separate commit later.

**Comment by mmontag** [comment]
Yea, I’ll update tonight, within about 8 hours. On May 21, 2024, at 1:34 PM, skjelten ***@***.***> wrote:﻿
I guess we should just push for a new release. Do you want to update this patch first? Moving to something like google style I suggest we do in one separate commit later.

**Comment by mmontag** [comment]
Updated

**Pull request merged**
